### ISSUE TITLE
Teleporting in different worlds

### ISSUE THREAD

**Issue by Gabbysimon** [MrButtersDEV/RTP-Me#8]
Okay, so basically, great plugin man. But I have a request for you. Basically, I am asking if you can set it so, if enabled in the config, when you type /rtp it will rtp you in a certain world, not the world you are in. This would be great for multiverse spawns and such. Thanks!

Layout:

spawn world > player types /rtp > if enabled in the config, the plugin, instead of teleporting the player inside of the spawn world, teleports the player to the survival world (world named survival)

**Comment by psychicgoldfish** [comment]
Good idea, I'll work on this

**Comment by MrButtersDEV** [comment]
Possible config example:
```
force-world:
    enabled: true
    world: worldname
```

**Comment by MrButtersDEV** [comment]
```java
# Should /rtp teleport you to this world and this world only?
# If set to "false" the user will be randomly placed in the world they are currently in
ForceWorld:
  enabled: false
  world: "world"
  ```
